export const initialState = {
  CurrentUser: {
    Name: "Narender Singh"
  },
  RequestForm: {
    Sections: [
      {
        "SectionId": 1,
        "Title": "Request_New_Section1",
        "TitleClass": "sectionHead",
        "IsSectionValid": true
      },
      {
        "SectionId": 2,
        "Title": "Request_New_Section2",
        "TitleClass": "sectionHead",
        "IsSectionValid": true
      },
      {
        "SectionId": 3,
        "Title": "Request_New_Section3",
        "TitleClass": "sectionHead",
        "IsSectionValid": true
      },
      {
        "SectionId": 4,
        "Title": "Request_New_Section4",
        "TitleClass": "sectionHead",
        "IsSectionValid": true
      },
      {
        "SectionId": 5,
        "Title": "Request_New_Section5",
        "TitleClass": "sectionHead",
        "IsSectionValid": true
      }
    ],
    IsFormValid: false,
    Fields: [
      {
        "ColumnName": "RMVControl",
        "FieldType": "RMVControl",
        "FieldSortOrder": 0,
        "FieldCssClass": "col-sm-12",
        "LookupType": "",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": true,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_RMVControl",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "text",
        "DataItemKey": "key",
        "ValidationMessage": "",
        "IsFieldValid": false,
        "SectionId": 1,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false,
        Controls: [
          [
            {
              ColumnName: 'RequestType',
              FieldType: 'DropDown',
              FieldSortOrder: 13,
              FieldCssClass: 'col-sm-4',
              LookupType: 'CascadingBased',
              UserSearchInRole: [],
              UserSearchDisplayColumn: '',
              ParentColumnName: '',
              ChildColumnName: 'RequestSubType',
              IsFieldChanger: false,
              IsRequired: true,
              HelpText: '',
              SourceListName: '',
              SourceColumnName: '',
              DefaultValue: '',
              PlaceholderText: 'Select',
              CustomValidatorFunction: '',
              ValidationType: {},
              FileUploadDirectory: '',
              ColumnDisplayTitle: 'Request_RequestType',
              ColumnDisplayTitleClass: 'label-default',
              IsRMVControl: true,
              DataRetrievalList: '',
              DataSavedList: 'Request',
              FieldValue: null,
              Controls: [],
              IsReadOnly: false,
              Data: [],
              DataItemText: 'Title',
              DataItemKey: 'ID',
              ValidationMessage: '',
              IsFieldValid: true,
              SectionId: 4,
              IsFieldLoading: false,
              IsFieldOpened: false,
              IsFieldSuggest: false
            },
            {
              ColumnName: 'RequestSubType',
              FieldType: 'DropDown',
              FieldSortOrder: 14,
              FieldCssClass: 'col-sm-4',
              LookupType: 'CascadingBased',
              UserSearchInRole: [],
              UserSearchDisplayColumn: '',
              ParentColumnName: 'RequestType',
              ChildColumnName: '',
              IsFieldChanger: false,
              IsRequired: true,
              HelpText: '',
              SourceListName: '',
              SourceColumnName: '',
              DefaultValue: '',
              PlaceholderText: 'Select',
              CustomValidatorFunction: '',
              ValidationType: {},
              FileUploadDirectory: '',
              ColumnDisplayTitle: 'Request_RequestSubType',
              ColumnDisplayTitleClass: 'label-default',
              IsRMVControl: true,
              DataRetrievalList: '',
              DataSavedList: 'Request',
              FieldValue: null,
              Controls: [],
              IsReadOnly: false,
              Data: [],
              DataItemText: 'Title',
              DataItemKey: 'ID',
              ValidationMessage: '',
              IsFieldValid: true,
              SectionId: 4,
              IsFieldLoading: false,
              IsFieldOpened: false,
              IsFieldSuggest: false
            },
            {
              ColumnName: 'Volume',
              FieldType: 'Number',
              FieldSortOrder: 16,
              FieldCssClass: 'col-sm-4',
              LookupType: '',
              UserSearchInRole: [],
              UserSearchDisplayColumn: '',
              ParentColumnName: '',
              ChildColumnName: '',
              IsFieldChanger: false,
              IsRequired: true,
              HelpText: '',
              SourceListName: '',
              SourceColumnName: '',
              DefaultValue: '',
              PlaceholderText: '',
              CustomValidatorFunction: '',
              ValidationType: {},
              FileUploadDirectory: '',
              ColumnDisplayTitle: 'Request_Volume',
              ColumnDisplayTitleClass: 'label-default',
              IsRMVControl: true,
              DataRetrievalList: '',
              DataSavedList: 'Request',
              FieldValue: null,
              Controls: [],
              IsReadOnly: false,
              Data: [],
              DataItemText: 'text',
              DataItemKey: 'key',
              ValidationMessage: '',
              IsFieldValid: true,
              SectionId: 4,
              IsFieldLoading: false,
              IsFieldOpened: false,
              IsFieldSuggest: false
            }
          ]
        ]
      },
      {
        "ColumnName": "Region",
        "FieldType": "DropDown",
        "FieldSortOrder": 2,
        "FieldCssClass": "col-sm-4",
        "LookupType": "UserBased",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "CoverageGroup",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "Request_Region_HelpText",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Request_Region_PlaceholderText",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_Region",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [
          {
            "ChartColourCode": "",
            "ID": 4,
            "IsActiveValue": true,
            "KeyName": "EMEA",
            "SortOrder": 1,
            "Title": "EMEA"
          },
          {
            "ChartColourCode": "",
            "ID": 2,
            "IsActiveValue": true,
            "KeyName": "Americas",
            "SortOrder": 2,
            "Title": "Americas"
          },
          {
            "ChartColourCode": "",
            "ID": 3,
            "IsActiveValue": true,
            "KeyName": "APAC",
            "SortOrder": 3,
            "Title": "APAC"
          }
        ],
        "DataItemText": "Title",
        "DataItemKey": "ID",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 1,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "CoverageGroup",
        "FieldType": "DropDown",
        "FieldSortOrder": 3,
        "FieldCssClass": "col-sm-4",
        "LookupType": "UserBased",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "Region",
        "ChildColumnName": "Requestor,RequestCoverageGroup",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Select",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_CoverageGroup",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "Title",
        "DataItemKey": "ID",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 1,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "Sector",
        "FieldType": "DropDown",
        "FieldSortOrder": 4,
        "FieldCssClass": "col-sm-4",
        "LookupType": "LookupBased",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Select",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_Sector",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "Request",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [
          {
            "ChartColourCode": "",
            "ID": 1,
            "IsActiveValue": true,
            "KeyName": "Office",
            "SortOrder": 1,
            "Title": "Office"
          },
          {
            "ChartColourCode": "",
            "ID": 2,
            "IsActiveValue": true,
            "KeyName": "Teams",
            "SortOrder": 2,
            "Title": "Teams"
          }
        ],
        "DataItemText": "Title",
        "DataItemKey": "ID",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 1,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "Requestor",
        "FieldType": "AutoComplete",
        "FieldSortOrder": 5,
        "FieldCssClass": "col-sm-4",
        "LookupType": "UserBased",
        "UserSearchInRole": [
          {
            "ID": 1,
            "Title": "Requestor"
          },
          {
            "ID": 2,
            "Title": "Gatekeeper"
          }
        ],
        "UserSearchDisplayColumn": "DisplayName,UserEmail",
        "ParentColumnName": "Region,CoverageGroup",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Select",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_Requestor",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "Title",
        "DataItemKey": "ID",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 1,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "CoOwner",
        "FieldType": "AutoCompleteMulti",
        "FieldSortOrder": 5,
        "FieldCssClass": "col-sm-4",
        "LookupType": "",
        "UserSearchInRole": [
          {
            "ID": 2,
            "Title": "Gatekeeper"
          },
          {
            "ID": 1,
            "Title": "Requestor"
          }
        ],
        "UserSearchDisplayColumn": "DisplayName,UserEmail",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Select",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_CoOwner",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "Title",
        "DataItemKey": "ID",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 1,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "AdditionalCoOwnerEmail",
        "FieldType": "Email",
        "FieldSortOrder": 6,
        "FieldCssClass": "col-sm-4",
        "LookupType": "",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": true,
        "HelpText": "Please enter email (Can enter multiple Id's separated by only comma)",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Please enter email ",
        "CustomValidatorFunction": "",
        "ValidationType": {
          "DateTimeFormat": "dd-MMM-yyyy hh:mm a",
          "Domain": "com|in",
          "Organization": "evs|agreeya|evalueserve",
          "RegExPattern": null,
          "MaxLength": null,
          "MinLength": null,
          "MinSize": null,
          "MaxSize": null,
          "AllowedExtensions": null
        },
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_AdditionalCoOwnerEmail",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "text",
        "DataItemKey": "key",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 1,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "RequestTitle",
        "FieldType": "TextBox",
        "FieldSortOrder": 7,
        "FieldCssClass": "col-sm-12",
        "LookupType": "",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": true,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Request Title",
        "CustomValidatorFunction": "",
        "ValidationType": {
          "DateTimeFormat": "dd-MMM-yyyy hh:mm a",
          "Domain": null,
          "Organization": null,
          "RegExPattern": null,
          "MaxLength": 30,
          "MinLength": null,
          "MinSize": null,
          "MaxSize": null,
          "AllowedExtensions": null
        },
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_RequestTitle",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "text",
        "DataItemKey": "key",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 2,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "ProjectCode",
        "FieldType": "TextBox",
        "FieldSortOrder": 8,
        "FieldCssClass": "col-sm-4",
        "LookupType": "",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Project Code",
        "CustomValidatorFunction": "",
        "ValidationType": {
          "DateTimeFormat": "dd-MMM-yyyy hh:mm a",
          "Domain": null,
          "Organization": null,
          "RegExPattern": null,
          "MaxLength": 10,
          "MinLength": null,
          "MinSize": null,
          "MaxSize": null,
          "AllowedExtensions": null
        },
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_ProjectCode",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "text",
        "DataItemKey": "key",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 2,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "RequestPriority",
        "FieldType": "DropDown",
        "FieldSortOrder": 9,
        "FieldCssClass": "col-sm-4",
        "LookupType": "LookupBased",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": true,
        "IsRequired": true,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Select",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_RequestPriority",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [
          {
            "ChartColourCode": "",
            "ID": 3,
            "IsActiveValue": true,
            "KeyName": "Low",
            "SortOrder": 1,
            "Title": "Low"
          },
          {
            "ChartColourCode": "",
            "ID": 2,
            "IsActiveValue": true,
            "KeyName": "Medium",
            "SortOrder": 2,
            "Title": "Medium"
          }
        ],
        "DataItemText": "Title",
        "DataItemKey": "ID",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 2,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "ExpectedDeliveryDateTime",
        "FieldType": "DateTime",
        "FieldSortOrder": 10,
        "FieldCssClass": "col-sm-4",
        "LookupType": "",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "wide",
        "CustomValidatorFunction": "",
        "ValidationType": {
          "AllowFutureDate": true,
          "AllowPastDate": false,
          "DateTimeFormat": "dd-MMM-yyyy hh:mm a",
          "Domain": null,
          "Organization": null,
          "RegExPattern": null,
          "MaxLength": null,
          "MinLength": null,
          "MinSize": null,
          "MaxSize": null,
          "AllowedExtensions": null
        },
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_ExpectedDeliveryDateTime",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "text",
        "DataItemKey": "key",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 2,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "RequestDescription",
        "FieldType": "RichTextBox",
        "FieldSortOrder": 11,
        "FieldCssClass": "col-sm-12",
        "LookupType": "",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": true,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_RequestDescription",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "text",
        "DataItemKey": "key",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 3,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "Effort",
        "FieldType": "Number",
        "FieldSortOrder": 12,
        "FieldCssClass": "col-sm-4",
        "LookupType": "",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_Effort",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "text",
        "DataItemKey": "key",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 4,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "RequestType",
        "FieldType": "DropDown",
        "FieldSortOrder": 13,
        "FieldCssClass": "col-sm-4",
        "LookupType": "CascadingBased",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "RequestSubType,Debt",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Select",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_RequestType",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": true,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [
          {
            "ChartColourCode": "",
            "ID": 2,
            "IsActiveValue": true,
            "KeyName": "IT",
            "SortOrder": 2,
            "Title": "IT"
          },
          {
            "ChartColourCode": "",
            "ID": 3,
            "IsActiveValue": true,
            "KeyName": "HR",
            "SortOrder": 3,
            "Title": "HR"
          },
          {
            "ChartColourCode": "",
            "ID": 4,
            "IsActiveValue": true,
            "KeyName": "Admin",
            "SortOrder": 4,
            "Title": "Admin"
          },
          {
            "ChartColourCode": "",
            "ID": 5,
            "IsActiveValue": true,
            "KeyName": "EMEA",
            "SortOrder": 5,
            "Title": "EMEA"
          }
        ],
        "DataItemText": "Title",
        "DataItemKey": "ID",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 4,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "Debt",
        "FieldType": "DropDown",
        "FieldSortOrder": 13,
        "FieldCssClass": "col-sm-4",
        "LookupType": "CascadingBased",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "RequestType",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Select",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_Debt",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "Request",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": true,
        "Data": [],
        "DataItemText": "Title",
        "DataItemKey": "ID",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 4,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "RequestSubType",
        "FieldType": "DropDownMulti",
        "FieldSortOrder": 14,
        "FieldCssClass": "col-sm-4",
        "LookupType": "CascadingBased",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "RequestType",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "Select",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_RequestSubType",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": true,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "Title",
        "DataItemKey": "ID",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 4,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "Volume",
        "FieldType": "Number",
        "FieldSortOrder": 16,
        "FieldCssClass": "col-sm-4",
        "LookupType": "",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": false,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "",
        "ColumnDisplayTitle": "Request_Volume",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": true,
        "DataRetrievalList": "",
        "DataSavedList": "Request",
        "FieldValue": null,
        "IsReadOnly": false,
        "Data": [],
        "DataItemText": "text",
        "DataItemKey": "key",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 4,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      },
      {
        "ColumnName": "Upload",
        "FieldType": "Upload",
        "FieldSortOrder": 20,
        "FieldCssClass": "col-sm-12",
        "LookupType": "",
        "UserSearchInRole": [],
        "UserSearchDisplayColumn": "",
        "ParentColumnName": "",
        "ChildColumnName": "",
        "IsFieldChanger": false,
        "IsRequired": true,
        "HelpText": "",
        "SourceListName": "",
        "SourceColumnName": "",
        "DefaultValue": "",
        "PlaceholderText": "",
        "CustomValidatorFunction": "",
        "ValidationType": {},
        "FileUploadDirectory": "DocLibraryTemp",
        "ColumnDisplayTitle": "Request_Upload",
        "ColumnDisplayTitleClass": "label-default",
        "IsRMVControl": false,
        "DataRetrievalList": "",
        "DataSavedList": "RequestDocument",
        "FieldValue": null,
        "IsReadOnly": true,
        "Data": [],
        "DataItemText": "text",
        "DataItemKey": "key",
        "ValidationMessage": "",
        "IsFieldValid": true,
        "SectionId": 5,
        "IsFieldLoading": false,
        "IsFieldOpened": false,
        "IsFieldSuggest": false
      }
    ],
    DropdownData: {
      MasterData: [
        {
          "ListName": "Region",
          "Values": [
            {
              "ChartColourCode": "",
              "ID": 4,
              "IsActiveValue": true,
              "KeyName": "EMEA",
              "SortOrder": 1,
              "Title": "EMEA"
            },
            {
              "ChartColourCode": "",
              "ID": 2,
              "IsActiveValue": true,
              "KeyName": "Americas",
              "SortOrder": 2,
              "Title": "Americas"
            },
            {
              "ChartColourCode": "",
              "ID": 3,
              "IsActiveValue": true,
              "KeyName": "APAC",
              "SortOrder": 3,
              "Title": "APAC"
            }
          ]
        },
        {
          "ListName": "RequestSubType",
          "Values": [
            {
              "ChartColourCode": "",
              "ID": 1,
              "IsActiveValue": true,
              "KeyName": "Industry",
              "SortOrder": 0,
              "Title": "Industry"
            },
            {
              "ChartColourCode": "",
              "ID": 2,
              "IsActiveValue": true,
              "KeyName": "Healthcare",
              "SortOrder": 0,
              "Title": "Healthcare"
            },
            {
              "ChartColourCode": "",
              "ID": 3,
              "IsActiveValue": true,
              "KeyName": "FIG",
              "SortOrder": 0,
              "Title": "FIG"
            },
            {
              "ChartColourCode": "",
              "ID": 4,
              "IsActiveValue": true,
              "KeyName": "MA",
              "SortOrder": 0,
              "Title": "MA"
            }
          ]
        },
        {
          "ListName": "Sector",
          "Values": [
            {
              "ChartColourCode": "",
              "ID": 1,
              "IsActiveValue": true,
              "KeyName": "Office",
              "SortOrder": 1,
              "Title": "Office"
            },
            {
              "ChartColourCode": "",
              "ID": 2,
              "IsActiveValue": true,
              "KeyName": "Teams",
              "SortOrder": 2,
              "Title": "Teams"
            }
          ]
        },
        {
          "ListName": "RequestPriority",
          "Values": [
            {
              "ChartColourCode": "",
              "ID": 3,
              "IsActiveValue": true,
              "KeyName": "Low",
              "SortOrder": 1,
              "Title": "Low"
            },
            {
              "ChartColourCode": "",
              "ID": 2,
              "IsActiveValue": true,
              "KeyName": "Medium",
              "SortOrder": 2,
              "Title": "Medium"
            },
            {
              "ChartColourCode": "",
              "ID": 1,
              "IsActiveValue": true,
              "KeyName": "High",
              "SortOrder": 3,
              "Title": "High"
            }
          ]
        },
        {
          "ListName": "RequestType",
          "Values": [
            {
              "ChartColourCode": "",
              "ID": 1,
              "IsActiveValue": true,
              "KeyName": "Sales",
              "SortOrder": 1,
              "Title": "Sales"
            },
            {
              "ChartColourCode": "",
              "ID": 2,
              "IsActiveValue": true,
              "KeyName": "IT",
              "SortOrder": 2,
              "Title": "IT"
            },
            {
              "ChartColourCode": "",
              "ID": 3,
              "IsActiveValue": true,
              "KeyName": "HR",
              "SortOrder": 3,
              "Title": "HR"
            },
            {
              "ChartColourCode": "",
              "ID": 4,
              "IsActiveValue": true,
              "KeyName": "Admin",
              "SortOrder": 4,
              "Title": "Admin"
            },
            {
              "ChartColourCode": "",
              "ID": 5,
              "IsActiveValue": true,
              "KeyName": "EMEA",
              "SortOrder": 5,
              "Title": "EMEA"
            }
          ]
        },
        {
          "ListName": "Debt",
          "Values": [
            {
              "ID": 1,
              "IsActiveValue": true,
              "KeyName": "Debt1",
              "SortOrder": 1,
              "Title": "Debt1"
            },
            {
              "ID": 2,
              "IsActiveValue": true,
              "KeyName": "Debt2",
              "SortOrder": 2,
              "Title": "Debt2"
            },
            {
              "ID": 3,
              "IsActiveValue": true,
              "KeyName": "Debt3",
              "SortOrder": 3,
              "Title": "Debt3"
            }
          ]
        },
        {
          "ListName": "RequestSubType",
          "Values": [
            {
              "ChartColourCode": "",
              "ID": 1,
              "IsActiveValue": true,
              "KeyName": "Software",
              "SortOrder": 1,
              "Title": "Software"
            },
            {
              "ChartColourCode": "",
              "ID": 2,
              "IsActiveValue": true,
              "KeyName": "Hardware",
              "SortOrder": 2,
              "Title": "Hardware"
            },
            {
              "ChartColourCode": "",
              "ID": 3,
              "IsActiveValue": true,
              "KeyName": "Network",
              "SortOrder": 3,
              "Title": "Network"
            },
            {
              "ChartColourCode": "",
              "ID": 4,
              "IsActiveValue": true,
              "KeyName": "Payroll",
              "SortOrder": 4,
              "Title": "Payroll"
            }
          ]
        }
      ],
      CascadingData: [
        {
          "Title": "",
          "ID": 1,
          "KeyName": "IT",
          "ParentKeyName": "",
          "ColumnName": "RequestType",
          "ParentColumnName": "",
          "ModuleName": {},
          "IsActive": true
        },
        {
          "Title": "",
          "ID": 2,
          "KeyName": "HR",
          "ParentKeyName": "",
          "ColumnName": "RequestType",
          "ParentColumnName": "",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "Software",
          "ID": 3,
          "KeyName": "Software",
          "ParentKeyName": "IT",
          "ColumnName": "RequestSubType",
          "ParentColumnName": "RequestType",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "Hardware",
          "ID": 4,
          "KeyName": "Hardware",
          "ParentKeyName": "IT",
          "ColumnName": "RequestSubType1",
          "ParentColumnName": "RequestType",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "Network",
          "ID": 5,
          "KeyName": "Network",
          "ParentKeyName": "HR",
          "ColumnName": "RequestSubType",
          "ParentColumnName": "RequestType",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "Admin",
          "ID": 7,
          "KeyName": "Admin",
          "ParentKeyName": "EMEA",
          "ColumnName": "RequestType",
          "ParentColumnName": "Region",
          "ModuleName": {},
          "IsActive": true
        },
        {
          "Title": "Payroll",
          "ID": 8,
          "KeyName": "Payroll",
          "ParentKeyName": "HR",
          "ColumnName": "RequestSubType",
          "ParentColumnName": "RequestType",
          "ModuleName": {},
          "IsActive": true
        },
        {
          "Title": "Title",
          "ID": 9,
          "KeyName": "APAC",
          "ParentKeyName": "",
          "ColumnName": "Region",
          "ParentColumnName": "",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "EMEA",
          "ID": 10,
          "KeyName": "EMEA",
          "ParentKeyName": "",
          "ColumnName": "Region",
          "ParentColumnName": "",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "Debt1",
          "ID": 11,
          "KeyName": "Debt1",
          "ParentKeyName": "IT",
          "ColumnName": "Debt",
          "ParentColumnName": "RequestType",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "Debt2",
          "ID": 12,
          "KeyName": "Debt2",
          "ParentKeyName": "HR",
          "ColumnName": "Debt",
          "ParentColumnName": "RequestType",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "EMEA",
          "ID": 13,
          "KeyName": "EMEA",
          "ParentKeyName": "",
          "ColumnName": "RequestType",
          "ParentColumnName": "",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "Healthcare",
          "ID": 14,
          "KeyName": "Healthcare",
          "ParentKeyName": "",
          "ColumnName": "CoverageGroup",
          "ParentColumnName": "",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "FIG",
          "ID": 15,
          "KeyName": "FIG",
          "ParentKeyName": "FIG",
          "ColumnName": "RequestCoverageGroup",
          "ParentColumnName": "CoverageGroup",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "Healthcare",
          "ID": 16,
          "KeyName": "Healthcare",
          "ParentKeyName": "FIG",
          "ColumnName": "RequestCoverageGroup",
          "ParentColumnName": "CoverageGroup",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        },
        {
          "Title": "Industry",
          "ID": 17,
          "KeyName": "Industry",
          "ParentKeyName": "FIG",
          "ColumnName": "RequestCoverageGroup",
          "ParentColumnName": "CoverageGroup",
          "ModuleName": {
            "ID": 1,
            "Title": "Request"
          },
          "IsActive": true
        }
      ],
      UserData: [
        {
          "Region": 3,
          "CoverageGroup": 2,
          "Sector": 2
        },
        {
          "Region": 4,
          "CoverageGroup": 2,
          "Sector": 1
        },
        {
          "Region": 2,
          "CoverageGroup": 3,
          "Sector": 1
        },
        {
          "Region": 4,
          "CoverageGroup": 3,
          "Sector": 1
        },
        {
          "Region": 2,
          "CoverageGroup": 1,
          "Sector": 1
        },
        {
          "Region": 4,
          "CoverageGroup": 2,
          "Sector": 1
        },
        {
          "Region": 4,
          "CoverageGroup": 2,
          "Sector": 2
        },
        {
          "Region": 4,
          "CoverageGroup": 2,
          "Sector": 1
        },
        {
          "Region": 4,
          "CoverageGroup": 2,
          "Sector": 1
        },
        {
          "Region": 4,
          "CoverageGroup": 2,
          "Sector": 1
        }
      ]
    }
  },
};